server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: easy-cut

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100           # JPA N+1 방지. 100개씩 묶어서 쿼리

  jackson:
    property-naming-strategy: LOWER_CAMEL_CASE  # 기본이지만 명시
    default-property-inclusion: non_null        # API 응담에서 Null은 제외해서 보냄 - 데이터 절약
    # 서버에서 시간 응답 포메팅
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false          # Default: true. → Unix Timestamp로 출력 됨.
